name: kamino
description: The ApolloTV app for iOS and Android.

# Version Code Format:
#  [Human Readable Version]+[MMIIRRT]

#  M => Major (xx)
#  I => Minor (xx)
#  R => Release (xx)
#  T => Type (0 => Prerelease, 1 => Beta, 2 => Release Candidate, 3 => Stable)
version: 1.2.0+102000

dependencies:
  # Core dependencies
  flutter:
    sdk: flutter

  rxdart: ^0.18.1

  # App dependencies
  cplayer:
    path: "cplayer"
  auto_size_text: ^0.2.1
  http: ^0.12.0
  package_info: ^0.3.2
  uni_links: ^0.1.3
  shared_preferences: ^0.4.3
  intl: ^0.15.7
  w_transport: ^3.2.8
  sqflite: ^0.12.2
  path_provider: ^0.4.1
  flutter_rating: ^0.0.1
  flutter_parallax: ^0.1.2
  logging: ^0.11.3+2
  dbcrypt: ^1.0.0
  flutter_material_color_picker: ^0.0.4
  url_launcher: ^4.0.2
  objectdb: ^1.0.5
  flutter_webview_plugin: ^0.3.0+2
  cached_network_image: ^0.5.1
  flutter_cache_manager: ^0.2.0+1
  dragable_flutter_list: ^1.0.2
  shimmer: ^0.0.6
  encrypt: ^1.0.0+1
  ota_update: ^0.1.2

# Compile-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.6.1"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/contributors.txt
    - assets/images/no_image_detail.jpg
    - assets/images/header.png
    - assets/images/header_text.png
    - assets/images/header_text_dark.png
    - assets/images/logo.png
    - assets/images/logo_foreground.png


  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: fonts/GlacialIndifference-Regular.otf
        - asset: fonts/GlacialIndifference-Bold.otf
          weight: 700
        - asset: fonts/GlacialIndifference-Italic.otf
          style: italic
    - family: apollotv-icons
      fonts:
        - asset: fonts/apollotv-icons.woff

# Set app icons
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  image_path_android: "images/google.png"
  image_path_ios: "images/apple.png"
  adaptive_icon_background: "images/logo_background.png"
  adaptive_icon_foreground: "images/logo_foreground.png"
